[build]
  publish = "."
  command = "echo 'Static site - no build needed'"

[[headers]]
  for = "/assets/images/badges/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "image/webp"
