[build]
  publish = "."
  command = "echo 'Static site - no build needed'"
[[headers]]
  for = "/assets/images/badges/*"  # Now points to correct folder
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
